# Generated by Django 6.1.1 on 2026-09-25 07:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the policy document (used for vector payload filtering)', max_length=64, unique=True)),
                ('document_name', models.CharField(help_text='Display name or original filename of the document', max_length=255)),
                ('file', models.FileField(help_text='Original PDF file stored on disk under media/policies/', upload_to='policies/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('indexed', 'Indexed in Qdrant'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('page_count', models.PositiveIntegerField(default=0, help_text='Total number of pages extracted from the PDF')),
                ('chunk_count', models.PositiveIntegerField(default=0, help_text='Total number of text chunks generated and indexed in Qdrant')),
                ('error_message', models.TextField(blank=True, help_text='Error details if processing failed', null=True)),
            ],
            options={
                'verbose_name': 'Policy Document',
                'verbose_name_plural': 'Policy Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
